"use client";

import ErrorState from "@/components/shared/ErrorState";
import LoadingSpinner from "@/components/shared/LoadingSpinner";
import { getPetByIdApi } from "@/lib/petsApi";
import { useQuery } from "@tanstack/react-query";
import { BadgeCheck, CircleDollarSign, HeartPulse, MapPin, PawPrint, ShieldCheck, UserRound } from "lucide-react";
import ProtectedRoute from "../shared/ProtectedRoute";
import AdoptionForm from "./AdoptionForm";

export default function PetDetailsShell({ petId }) {
  const { data, isLoading, isError } = useQuery({ queryKey: ["pet-details", petId], queryFn: () => getPetByIdApi(petId), enabled: Boolean(petId) });
  const pet = data?.pet;
  return <ProtectedRoute><section className="section-padding bg-orange-50"><div className="container-custom">{isLoading && <LoadingSpinner message="Loading pet details..." />}{isError && <ErrorState title="Pet details could not be loaded" message="Please check your server connection or try again later." />}{!isLoading && !isError && !pet && <ErrorState title="Pet not found" message="This pet listing may have been removed." />}{!isLoading && !isError && pet && <div className="grid gap-8 lg:grid-cols-[1.25fr_0.75fr]"><div><div className="overflow-hidden rounded-[32px] bg-white shadow-sm"><div className="relative"><img src={pet.image} alt={pet.petName} className="h-[420px] w-full object-cover" /><span className={`absolute right-5 top-5 rounded-full px-5 py-2 text-sm font-bold ${pet.status === "adopted" ? "bg-slate-950 text-white" : "bg-green-600 text-white"}`}>{pet.status === "adopted" ? "Adopted" : "Available"}</span></div><div className="p-6 md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><p className="mb-3 inline-flex items-center gap-2 rounded-full bg-orange-100 px-5 py-2 text-sm font-bold text-orange-700"><PawPrint size={16} />{pet.species}</p><h1 className="text-4xl font-black text-slate-950">{pet.petName}</h1><p className="mt-3 flex items-center gap-2 font-semibold text-slate-500"><MapPin size={18} className="text-orange-500" />{pet.location}</p></div><div className="rounded-3xl bg-orange-50 px-6 py-4 text-center"><p className="text-sm font-bold text-orange-700">Adoption Fee</p><p className="mt-1 text-3xl font-black text-slate-950">${pet.adoptionFee}</p></div></div><div className="mt-8 grid gap-4 md:grid-cols-2"><InfoCard icon={PawPrint} label="Breed" value={pet.breed} /><InfoCard icon={BadgeCheck} label="Age" value={`${pet.age} year${Number(pet.age) > 1 ? "s" : ""}`} /><InfoCard icon={UserRound} label="Gender" value={pet.gender} /><InfoCard icon={HeartPulse} label="Health Status" value={pet.healthStatus} /><InfoCard icon={ShieldCheck} label="Vaccination" value={pet.vaccinationStatus} /><InfoCard icon={CircleDollarSign} label="Fee" value={`$${pet.adoptionFee}`} /></div><div className="mt-8 rounded-3xl bg-orange-50 p-6"><h2 className="text-2xl font-black text-slate-950">Description</h2><p className="mt-3 leading-8 text-slate-700">{pet.description}</p></div><div className="mt-6 rounded-3xl border border-orange-100 p-6"><h2 className="text-xl font-black text-slate-950">Owner Information</h2><p className="mt-2 text-slate-600">Owner Name: <span className="font-bold">{pet.ownerName}</span></p><p className="mt-1 text-slate-600">Owner Email: <span className="font-bold">{pet.ownerEmail}</span></p></div></div></div></div><div className="lg:sticky lg:top-24 lg:self-start"><AdoptionForm pet={pet} /></div></div>}</div></section></ProtectedRoute>;
}
function InfoCard({ icon: Icon, label, value }) { return <div className="rounded-3xl border border-orange-100 p-5"><Icon className="text-orange-600" size={24} /><p className="mt-3 text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-lg font-black text-slate-950">{value}</p></div>; }
