"use client";

import { approveRequestApi, getPetRequestsApi, rejectRequestApi } from "@/lib/requestsApi";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Mail, X, XCircle } from "lucide-react";
import toast from "react-hot-toast";
import EmptyState from "../shared/EmptyState";
import ErrorState from "../shared/ErrorState";
import LoadingSpinner from "../shared/LoadingSpinner";

export default function RequestsModal({ open, pet, onClose }) {
  const queryClient = useQueryClient();
  const { data, isLoading, isError } = useQuery({ queryKey: ["pet-requests", pet?._id], queryFn: () => getPetRequestsApi(pet._id), enabled: Boolean(open && pet?._id) });
  const approveMutation = useMutation({ mutationFn: approveRequestApi, onSuccess: (response) => { toast.success(response.message || "Request approved"); queryClient.invalidateQueries({ queryKey: ["pet-requests", pet?._id] }); queryClient.invalidateQueries({ queryKey: ["my-listings"] }); queryClient.invalidateQueries({ queryKey: ["pets"] }); queryClient.invalidateQueries({ queryKey: ["featured-pets"] }); }, onError: (error) => toast.error(error?.response?.data?.message || "Failed to approve request") });
  const rejectMutation = useMutation({ mutationFn: rejectRequestApi, onSuccess: (response) => { toast.success(response.message || "Request rejected"); queryClient.invalidateQueries({ queryKey: ["pet-requests", pet?._id] }); queryClient.invalidateQueries({ queryKey: ["my-listings"] }); }, onError: (error) => toast.error(error?.response?.data?.message || "Failed to reject request") });
  if (!open) return null;
  const requests = data?.requests || [];
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 px-4"><div className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-[32px] bg-white p-6 shadow-2xl"><div className="mb-6 flex items-start justify-between gap-4"><div><p className="mb-2 inline-block rounded-full bg-orange-100 px-4 py-2 text-sm font-bold text-orange-700">Adoption Requests</p><h2 className="text-3xl font-black text-slate-950">{pet?.petName}</h2><p className="mt-2 text-slate-600">Review adoption requests and approve the best match.</p></div><button type="button" onClick={onClose} className="rounded-full bg-slate-100 p-2 text-slate-600 hover:bg-slate-200"><X /></button></div>{isLoading && <LoadingSpinner message="Loading requests..." />}{isError && <ErrorState title="Failed to load requests" message="Please check your login session or server connection." />}{!isLoading && !isError && requests.length === 0 && <EmptyState title="No requests yet" message="No adopter has submitted a request for this pet yet." />}{!isLoading && !isError && requests.length > 0 && <div className="space-y-4">{requests.map((request) => <div key={request._id} className="rounded-3xl border border-orange-100 p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><div className="flex flex-wrap items-center gap-3"><h3 className="text-xl font-black text-slate-950">{request.requesterName}</h3><span className={statusClass(request.status)}>{request.status}</span></div><p className="mt-2 flex items-center gap-2 text-sm font-semibold text-slate-500"><Mail size={16} />{request.requesterEmail}</p><p className="mt-3 text-sm font-bold text-orange-700">Pickup Date: {formatDate(request.pickupDate)}</p><p className="mt-3 leading-7 text-slate-600">{request.message}</p></div>{request.status === "pending" && <div className="flex gap-2"><button type="button" onClick={() => approveMutation.mutate(request._id)} disabled={approveMutation.isPending || rejectMutation.isPending} className="flex items-center gap-2 rounded-2xl bg-green-600 px-4 py-2 font-bold text-white transition hover:bg-green-700 disabled:opacity-60"><CheckCircle2 size={17} />Approve</button><button type="button" onClick={() => rejectMutation.mutate(request._id)} disabled={approveMutation.isPending || rejectMutation.isPending} className="flex items-center gap-2 rounded-2xl bg-red-600 px-4 py-2 font-bold text-white transition hover:bg-red-700 disabled:opacity-60"><XCircle size={17} />Reject</button></div>}</div></div>)}</div>}</div></div>;
}
function statusClass(status) { if (status === "approved") return "rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-700"; if (status === "rejected") return "rounded-full bg-red-100 px-3 py-1 text-xs font-bold text-red-700"; return "rounded-full bg-orange-100 px-3 py-1 text-xs font-bold text-orange-700"; }
function formatDate(date) { if (!date) return "N/A"; return new Date(date).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" }); }
